#!/usr/bin/env bash

if [ -z "${CHANGE_LOG_FILE}" ]
then
    CHANGE_LOG_FILE="db.changelog.yml"
fi

if [ -z "${SLEEP}" ]
then
    SLEEP=1
fi

sleep ${SLEEP}

liquibase \
    --classpath="/usr/local/bin/postgresql-42.0.0.jar" \
    --changeLogFile="/changelogs/${CHANGE_LOG_FILE}" \
    --url="jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}" \
    --username=${DB_USERNAME} \
    --password=${DB_PASSWORD} \
    generateChangeLog
